[project]
name = "mentor-bahasa-inggris-virtual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yudigf", email = "yudi.fitory@wgs-id.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.19.0",
    "loguru>=0.7.3",
    "markdown-pdf>=1.13.3",
    "pydantic>=2.0.0",
    "python-dotenv>=1.2.3",
    "python-telegram-bot[job-queue]>=22.8",
    "supabase>=2.31.0",
    "telegramify-markdown>=1.2.0",
    "tzdata>=2026.3",
]

[project.scripts]
mentor-bahasa-inggris-virtual = "mentor_bahasa_inggris_virtual:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
